version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
