version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/
    ports:
      - 3001:3001
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:80
  redis-db:
    container_name: redis-db
    image: redis:alpine
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - ./backend/.env
