version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/
    ports:
      - 3001:3001
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/
    depends_on:
      - backend
    ports:
      - 3000:80
